### ISSUE TITLE
My server fail to start

### ISSUE THREAD

**Issue by gustavocastrov** [jorgegorka/svelte-firebase#18]
Hello Jorge
I am excited to dive into your template. Unfortunately I couldn't get started.
I created a Firebase app. (First time!) I am new to Firebase.
I couldn't get a Wep Api Key from Firebase, so I let it black on the config file.  [Maybe this is the reason of what I am going to describe next].
Bottom line:  
See below copy pasted of my terminal after I run [yarn dev]
It stop on waiting for changes [/bundle.js] .
My browser on http://localhost:5000/ keep spinning waiting for something.
Running node v12.18.3)  npm 6.14.6
My development machine. Linux Ubuntu 20.04
Suggestions? Thank You!
//////  terminal log  ////////////////////////////////
joedoe@dev:~/www/svelte/samples/svelte-firebase$ yarn dev
yarn run v1.22.5
$ run-p start:dev autobuild
$ sirv public -s --dev
$ rollup -c -w

  Your application is ready~! 🚀

  - Local:      http://localhost:5000
  - Network:    Add `--host` to expose

────────────────── LOGS ──────────────────

rollup v2.30.0
bundles src/main.js → public/bundle.js...
LiveReload enabled
(!) Plugin svelte: A11y: '#' is not a valid href attribute
src/views/admin/dashboard/index.svelte
14:       </div>
15:       <div class="card-action">
16:         <a href="#">This is a link</a>
               ^
17:         <a href="#">This is a link</a>
18:       </div>
src/views/admin/dashboard/index.svelte
15:       <div class="card-action">
16:         <a href="#">This is a link</a>
17:         <a href="#">This is a link</a>
               ^
18:       </div>
19:     </div>
src/views/admin/dashboard/index.svelte
32:       </div>
33:       <div class="card-action">
34:         <a href="#">This is a link</a>
               ^
35:       </div>
36:     </div>
src/views/admin/dashboard/index.svelte
46:         </div>
47:         <div class="card-action">
48:           <a href="#">This is a link</a>
                 ^
49:         </div>
50:       </div>
src/views/admin/teams/index.svelte
60:     </div>
61:     <div class="col s3">
62:       <a href="#" class="btn light-blue darken-1 secondary-content new-team" on:click={addTeam}>
             ^
63:         New team
64:         <i class="material-icons left">add</i>
src/views/public/home/menu.svelte
31:       </li>
32:     </ul>
33:     <a href="#" data-target="nav-mobile" class="sidenav-trigger">
           ^
34:       <i class="material-icons">menu</i>
35:     </a>
src/views/admin/layout/header.svelte
34:       <i class="material-icons left">web</i>
35:     </a>
36:     <a href="#" data-target="mobile-demo" class="sidenav-trigger">
           ^
37:       <i class="material-icons">menu</i>
38:     </a>
src/views/admin/layout/header.svelte
39:     <ul class="right hide-on-med-and-down">
40:       <li>
41:         <a href="#" class="dropdown-trigger" id="dropdownSettings" data-target="settingsMenu">
               ^
42:           <i class="material-icons left">settings</i>
43:           Settings
src/views/admin/layout/header.svelte
46: 
47:           <li>
48:             <a href="#" on:click={logoutUser}>
                   ^
49:               Log out
50:               <i class="material-icons left">exit_to_app</i>
src/views/admin/layout/header.svelte
76:   </li>
77:   <li>
78:     <a href="#" on:click={logoutUser}>
           ^
79:       Log out
80:       <i class="material-icons left">exit_to_app</i>
src/views/admin/employees/item.svelte
47:   <td>{employee.role}</td>
48:   <td>
49:     <a href="#" on:click={removeEmployee} class="secondary-content" title={statusTitle()}>
           ^
50:       <i class="material-icons">{statusIcon()}</i>
51:     </a>
src/views/admin/teams/item.svelte
27:   <td>
28:     {#if team.employeesCount === 0}
29:       <a href="#" on:click={removeTeam} class="secondary-content" title="Delete {team.name}">
             ^
30:         <i class="material-icons">delete</i>
31:       </a>
src/views/admin/teams/item.svelte
31:       </a>
32:     {/if}
33:     <a href="#" on:click={editTeam} class="secondary-content edit-icon" title="Edit {team.name}">
           ^
34:       <i class="material-icons">edit</i>
35:     </a>
src/views/admin/employees/header/search.svelte
28:   <div class="col s12 m3">
29:     {#if active}
30:       <a href="#" on:click={toggleActive} class="btn-flat yellow lighten-1 black-text secondary-content new-action">
             ^
31:         Show inactive
32:         <i class="material-icons left">archive</i>
src/views/admin/employees/header/search.svelte
33:       </a>
34:     {:else}
35:       <a href="#" on:click={toggleActive} class="btn-flat green accent-1 black-text secondary-content new-action">
             ^
36:         Show active
37:         <i class="material-icons left">unarchive</i>
(!) Plugin svelte: A11y: <img> element should have an alt attribute
src/views/admin/dashboard/index.svelte
22:     <div class="card">
23:       <div class="card-image">
24:         <img src="/images/almond.jpg" />
            ^
25:         <span class="card-title">Card Title</span>
26:       </div>
src/views/admin/dashboard/index.svelte
39:     <div class="card horizontal">
40:       <div class="card-image">
41:         <img src="/images/waterfall.jpg" />
            ^
42:       </div>
43:       <div class="card-stacked">
(!) Plugin svelte: Form has unused export property 'showModal'. If it is for external reference only, please consider using `export const showModal`
src/views/admin/employees/form.svelte
15: 
16:   export let employee = { name: '', email: '', password: '', teamId: '' }
17:   export let showModal = false
                 ^
18:   let loading = true
19: 
(!) Plugin svelte: A11y: Avoid using autofocus
src/views/components/forms/password_input.svelte
22:     {id}
23:     class:invalid={error}
24:     autofocus={isFocused}
        ^
25:     on:blur />
26:   <label for={id}>{label}</label>
src/views/components/forms/email_input.svelte
22:     class="validate"
23:     class:invalid={error}
24:     autofocus={isFocused}
        ^
25:     on:blur />
26:   <label for={id}>{label}</label>
src/views/components/forms/text_input.svelte
27:     {id}
28:     class:invalid={error}
29:     autofocus={isFocused}
        ^
30:     on:blur />
31:   <label for={id}>{label}</label>
(!) Plugin svelte: Select has unused export property 'inputName'. If it is for external reference only, please consider using `export const inputName`
src/views/components/forms/select.svelte
2:   import { afterUpdate } from 'svelte'
3: 
4:   export let inputName = 'select'
                ^
5:   export let id = 'selectElement'
6:   export let label = 'Select'
(!) Plugin svelte: Buttons has unused export property 'buttonColor'. If it is for external reference only, please consider using `export const buttonColor`
src/views/components/modals/buttons.svelte
2:   export let cancelText = 'No'
3:   export let cancelButton = true
4:   export let buttonColor = 'teal'
                ^
5:   export let submitText = 'Yes'
6:   export let isLoading = false
(!) Plugin svelte: Buttons has unused export property 'confirmInfo'. If it is for external reference only, please consider using `export const confirmInfo`
src/views/components/modals/buttons.svelte
 5:   export let submitText = 'Yes'
 6:   export let isLoading = false
 7:   export let confirmInfo = {}
                 ^
 8:   import { createEventDispatcher } from 'svelte'
 9: 
(!) Plugin svelte: Menu has unused export property 'employeeId'. If it is for external reference only, please consider using `export const employeeId`
src/views/admin/layout/sidebar/menu.svelte
3: 
4:   export let items = []
5:   export let employeeId = null
                ^
6: </script>
7: 
created public/bundle.js in 5s

[2020-10-14 12:22:00] waiting for changes...
  [12:22:33] 200 ─ 4.95ms ─ /
  [12:22:33] 200 ─ 0.60ms ─ /global.css
  [12:22:33] 200 ─ 1.98ms ─ /stylesheets/custom.css
  [12:22:33] 404 ─ 0.22ms ─ /bundle.css
  [12:22:33] 200 ─ 2.29ms ─ /plugins.css
  [12:22:33] 200 ─ 7.87ms ─ /bundle.js

**Comment by jorgegorka** [comment]
Hi @gustavocastrov 

In this link you will find information about how to generate a Web API Key:  https://stackoverflow.com/questions/13863297/firebase-what-is-the-api-key
