### ISSUE TITLE
Indefinite Reload

### ISSUE THREAD

**Issue by mrismail91** [jorgegorka/svelte-firebase#5]
When I run yarn run dev my localhost auto-refreshes every second with no errors, giving you no time to do anything. I don't what the problem is and also to mention I can see all my bundle files (bundle.js, bundle.css, etc.) in my public folder but there greyed out. When my localhost runs it automatically goes to localhost:5000/404.html

**Comment by tomatrow** [comment]
Hi. It seems that the upgrade of [svelte-router](https://github.com/jorgegorka/svelte-router) in 0e765a66f9f3b3524a3ccd09931f37ad0281850d  from version 2 to 5 may have had something to do with it. I made a [pull request with fixes](#6).
